### ISSUE TITLE
Error in xopt-pydantic communication

### ISSUE THREAD

**Issue by wyrnat** [SLAC-ML/Badger#9]
I do not believe this is a Badger problem, but I cannot start Badger developer version with the current master commit [9fdd2bf] because of the following error. I have not updated Badger for at least 1-2 monthes, so I cannot say with which commit this problem occured
It seems to be a problem with pydantic-xopt communication, but since both packages are installed via setup.py (and I create a clean venv before the installation process), I think this error should also occur for other users. Can somebody confirm this?

Traceback (most recent call last):
  File "/home/woehnert/Software/Badger-Env/.badger_venv_Linux/bin/badger", line 5, in <module>
    from badger.__main__ import main
  File "/home/woehnert/Software/Badger-Env/Badger/src/badger/__main__.py", line 14, in <module>
    from .actions.run import run_routine
  File "/home/woehnert/Software/Badger-Env/Badger/src/badger/actions/run.py", line 11, in <module>
    from ..core import run_routine as run
  File "/home/woehnert/Software/Badger-Env/Badger/src/badger/core.py", line 11, in <module>
    from xopt import Generator
  File "/home/woehnert/Software/Badger-Env/.badger_venv_Linux/lib/python3.9/site-packages/xopt/__init__.py", line 2, in <module>
    from xopt.asynchronous import AsynchronousXopt
  File "/home/woehnert/Software/Badger-Env/.badger_venv_Linux/lib/python3.9/site-packages/xopt/asynchronous.py", line 9, in <module>
    from xopt.base import logger, Xopt
  File "/home/woehnert/Software/Badger-Env/.badger_venv_Linux/lib/python3.9/site-packages/xopt/base.py", line 18, in <module>
    from xopt.evaluator import Evaluator, validate_outputs
  File "/home/woehnert/Software/Badger-Env/.badger_venv_Linux/lib/python3.9/site-packages/xopt/evaluator.py", line 14, in <module>
    from xopt.utils import get_function, get_function_defaults, safe_call
  File "/home/woehnert/Software/Badger-Env/.badger_venv_Linux/lib/python3.9/site-packages/xopt/utils.py", line 16, in <module>
    from xopt.generator import Generator
  File "/home/woehnert/Software/Badger-Env/.badger_venv_Linux/lib/python3.9/site-packages/xopt/generator.py", line 10, in <module>
    from xopt.vocs import VOCS
  File "/home/woehnert/Software/Badger-Env/.badger_venv_Linux/lib/python3.9/site-packages/xopt/vocs.py", line 37, in <module>
    class VOCS(XoptBaseModel):
  File "/home/woehnert/Software/Badger-Env/.badger_venv_Linux/lib/python3.9/site-packages/xopt/vocs.py", line 43, in VOCS
    variables: Dict[str, conlist(float, min_length=2, max_length=2)] = Field(
  File "/home/woehnert/Software/Badger-Env/.badger_venv_Linux/lib/python3.9/site-packages/pydantic/types.py", line 865, in conlist
    return Annotated[List[item_type], annotated_types.Len(min_length or 0, max_length)]
TypeError: Len() takes no arguments

**Comment by wyrnat** [comment]
Update: With the new pip version of badger-opt (1.0.1) I got the same problem. The previous version (I guess 0.11) was still working for me

**Comment by wenatuhs** [comment]
Issue should be resolved w/ the recent versions of [Badger](https://github.com/xopt-org/Badger)/[Xopt](https://github.com/xopt-org/Xopt)
